run:
  modules-download-mode: readonly

linters:
  disable:
    - depguard
    - exhaustruct
    - paralleltest
    - protogetter
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/MartyHub)
    custom-order: true
