// Code generated by github.com/MartyHub/sqlc-pg version dev
// DO NOT EDIT

package sqlc

const (
	BookTypeFiction    = "FICTION"
	BookTypeNonfiction = "NONFICTION"
)

type BookType string

const (
	TableAuthors = "authors"
	TableBooks   = "books"
)
