// Code generated by github.com/MartyHub/sqlc-pg version dev
// DO NOT EDIT

package sqlc

const (
	StatusOpEn   = "op!en"
	StatusCloSed = "clo@sed"
)

type Status string

const (
	TableCity  = "city"
	TableVenue = "venue"
)
